



export const initialData : any = [
  {
    id: 1,
    campaign: "Campaign 1",
    mainType: "Premium",
    subType: "Top",
    limitedRepeatance: true,
    inSession: "Session 1",
    sessionHandler: "Handler 1",
  },
  {
    id: 2,
    campaign: "Campaign 2",
    mainType: "Burn",
    subType: "Latest",
    limitedRepeatance: false,
    inSession: "Session 2",
    sessionHandler: "Handler 2",
  },
  {
    id: 3,
    campaign: "Campaign 3",
    mainType: "Premium",
    subType: "Top",
    limitedRepeatance: false,
    inSession: "Session 3",
    sessionHandler: "Handler 3",
  },
  {
    id: 4,
    campaign: "Campaign 4",
    mainType: "Burn",
    subType: "Latest",
    limitedRepeatance: true,
    inSession: "Session 4",
    sessionHandler: "Handler 4",
  },
  {
    id: 5,
    campaign: "Campaign 5",
    mainType: "Premium",
    subType: "Top",
    limitedRepeatance: true,
    inSession: "Session 5",
    sessionHandler: "Handler 5",
  },
  {
    id: 6,
    campaign: "Campaign 6",
    mainType: "Burn",
    subType: "Top",
    limitedRepeatance: false,
    inSession: "Session 6",
    sessionHandler: "Handler 6",
  },
  {
    id: 7,
    campaign: "Campaign 7",
    mainType: "Premium",
    subType: "Latest",
    limitedRepeatance: true,
    inSession: "Session 7",
    sessionHandler: "Handler 7",
  },
  {
    id: 8,
    campaign: "Campaign 8",
    mainType: "Burn",
    subType: "Top",
    limitedRepeatance: false,
    inSession: "Session 8",
    sessionHandler: "Handler 8",
  },
  {
    id: 9,
    campaign: "Campaign 9",
    mainType: "Premium",
    subType: "Top",
    limitedRepeatance: true,
    inSession: "Session 9",
    sessionHandler: "Handler 9",
  },
  {
    id: 10,
    campaign: "Campaign 10",
    mainType: "Burn",
    subType: "Latest",
    limitedRepeatance: false,
    inSession: "Session 10",
    sessionHandler: "Handler 10",
  },
];


export const columns = [
  { name: "ID", uid: "id" },
  { name: "Campaign", uid: "campaign" },
  { name: "Main Type", uid: "mainType", filterOptions: ["Premium", "Burn"] },
  { name: "Sub Type", uid: "subType", filterOptions: ["Top", "Latest"] },
  { name: "Limited Repeatance", uid: "limitedRepeatance" },
  { name: "In Session", uid: "inSession" },
  { name: "Session Handler", uid: "sessionHandler" },
];
