export const initialData = [
  {
    id: 1,
    campaignName: "Campaign A",
    sessionNiche: "Niche 1",
    burnerBots: "Bot A",
    isActive: true,
  },
  {
    id: 2,
    campaignName: "Campaign B",
    sessionNiche: "Niche 2",
    burnerBots: "Bot B",
    isActive: false,
  },
  {
    id: 3,
    campaignName: "Campaign C",
    sessionNiche: "Niche 3",
    burnerBots: "Bot C",
    isActive: true,
  },
  {
    id: 4,
    campaignName: "Campaign D",
    sessionNiche: "Niche 4",
    burnerBots: "Bot D",
    isActive: false,
  },
  {
    id: 5,
    campaignName: "Campaign E",
    sessionNiche: "Niche 5",
    burnerBots: "Bot E",
    isActive: true,
  },
  {
    id: 6,
    campaignName: "Campaign F",
    sessionNiche: "Niche 6",
    burnerBots: "Bot F",
    isActive: false,
  },
  {
    id: 7,
    campaignName: "Campaign G",
    sessionNiche: "Niche 7",
    burnerBots: "Bot G",
    isActive: true,
  },
  {
    id: 8,
    campaignName: "Campaign H",
    sessionNiche: "Niche 8",
    burnerBots: "Bot H",
    isActive: false,
  },
  {
    id: 9,
    campaignName: "Campaign I",
    sessionNiche: "Niche 9",
    burnerBots: "Bot I",
    isActive: true,
  },
  {
    id: 10,
    campaignName: "Campaign J",
    sessionNiche: "Niche 10",
    burnerBots: "Bot J",
    isActive: false,
  },
];

export const columns = [
  { name: "", uid: "selectAll" },
  { name: "ID", uid: "id" },
  { name: "Campaign Name", uid: "campaignName" },
  { name: "Session Niche", uid: "sessionNiche" },
  { name: "Burner Bots", uid: "burnerBots" },
  { name: "Is Active", uid: "isActive", filterOptions: ["Yes", "No"] },
];
